### GET request to example server
GET http://localhost:8080/kategori
###
GET http://localhost:8080/kategori/star
###
POST localhost:8080/kategori
Content-Type: application/json

{
  "name": "tester",
  "symbol": "dator",
  "description": "en bild på en dator"
}

###
GET http://localhost:8080/locations/public/all
###
GET http://localhost:8080/locations/public/1
###
GET http://localhost:8080/locations/all
###
GET http://localhost:8080/locations/public/category/1


###
GET http://localhost:8080/locations/1003
###
GET http://localhost:8080/locations/remove/4
###
POST localhost:8080/locations/add
Content-Type: application/json

{
  "name": "Stockholm",
  "kategori": 2,
  "userId": 1003,
  "isPrivate": false,
  "description": "Capital of Sweden",
  "longitude": 18.0686,
  "latitude": 59.3293
}
###
PUT http://localhost:8080/locations/edit/5
Content-Type: application/json

{
  "name": "Stockholm",
  "kategori": 1,
  "isPrivate": false,
  "description": "Edited Capital of Sweden"
}