### 
GET http://localhost:8080/api/category

###
GET http://localhost:8080/api/category/star

###
POST localhost:8080/api/category
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "tester",
  "symbol": "dator",
  "description": "en bild på en dator"
}


###

POST https://fungover.org/auth
Content-Type: application/json

{
  "username": "martin",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.access_token); %}

###

GET http://localhost:8080/api/locations/1
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/api/locations/all
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/api/locations/public/category/1
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/api/locations/remove/4
Authorization: Bearer {{auth_token}}

###
POST localhost:8080/api/locations

Content-Type: application/json

Authorization: Bearer {{auth_token}}

{
  "name": "Stockholm",
  "api/category": 2,
  "userId": "martin",
  "isPrivate": false,
  "description": "Capital of Sweden",
  "latitude": 59.3293,
  "longitude": 18.0686
}


###
PUT http://localhost:8080/api/locations/edit/5

Content-Type: application/json

{
  "name": "Stockholm",
  "api/category": 1,
  "isPrivate": false,
  "description": "Edited Capital of Sweden"
}

Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/api/locations/radius/2/54.06/10000
Authorization: Bearer {{auth_token}}

###
